Fix the HTTPRPCONLY
TsuyoshiUshio/azure-functions-java-worker pull request #1
Opened 2020-05-03 01:51 UTC by amamounelsayed

2020-05-04 01:14 UTC, TsuyoshiUshio requested changes
I care only the port part! :) Anything else is LGTM!

2020-05-04 01:14 UTC, TsuyoshiUshio commented on src/main/java/com/microsoft/azure/functions/worker/binding/BindingDataStore.java
> +        if(data.getDataCase().equals(TypedData.DataCase.STRING) && headerMap.get("content-type") != null && contentType.equals("application/json")) {
I just want to know why you change the condition? I'd like to know the reason. 
This is not objection. I just want to know the reason. :)

2020-05-04 01:14 UTC, TsuyoshiUshio commented on src/test/java/com/microsoft/azure/functions/worker/binding/tests/BindingDataStoreTests.java
> +public class BindingDataStoreTests {
It helps me to understand the context. Thanks!

2020-05-04 01:14 UTC, TsuyoshiUshio commented on src/test/java/com/microsoft/azure/functions/worker/test/utilities/FunctionsTestHost.java
> +    public int getPort() { return 55005; }
We need to discuss this point. In my enviornment 55005 is already used. The address is too high, so OS could use it. (It depend on the enviornment) Is there any good port to avoid the issue?

2020-05-04 01:14 UTC, TsuyoshiUshio commented on src/test/java/com/microsoft/azure/functions/worker/test/utilities/FunctionsTestHost.java
> +    public int getPort() { return 55005; }
I've done quick research. gPRC doesn't have register port. 
https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers
gRPC doesn't seem to have particular default port. the official uses 50051
https://grpc.io/docs/guides/auth/
ASP.NET Core gRPC seems 5001 https://docs.microsoft.com/ja-jp/aspnet/core/tutorials/grpc/grpc-start?view=aspnetcore-3.1&tabs=visual-studio Hmm...

2020-05-04 01:14 UTC, TsuyoshiUshio commented on src/test/java/com/microsoft/azure/functions/worker/test/utilities/FunctionsTestHost.java
> +    public int getPort() { return 55005; }
I found an document. We need to avoid 49152-65535 for Windows. Windows dynamically allocate the port range. So if you are lucky, it works, if not, fail. 
https://support.microsoft.com/en-us/help/929851/the-default-dynamic-port-range-for-tcp-ip-has-changed-in-windows-vista?fbclid=IwAR2fQE4gG3GAg_As5vzDYCl0VPLNnLVSQ2yjwQ0jebt7xzqpylfkx2tFl-s

2020-05-04 17:06 UTC, amamounelsayed commented on src/main/java/com/microsoft/azure/functions/worker/binding/BindingDataStore.java
> +        if(data.getDataCase().equals(TypedData.DataCase.STRING) && headerMap.get("content-type") != null && contentType.equals("application/json")) {
This is for safety check, in case the data came not in String format, it will cause null pointer exception. This should not happen but it may.

2020-05-04 17:07 UTC, amamounelsayed commented on src/test/java/com/microsoft/azure/functions/worker/binding/tests/BindingDataStoreTests.java
> +public class BindingDataStoreTests {
Didn't get the question?

2020-05-04 17:12 UTC, amamounelsayed commented on src/test/java/com/microsoft/azure/functions/worker/test/utilities/FunctionsTestHost.java
> +    public int getPort() { return 55005; }
Sounds good, it failed for me when I was running the application in my local machine and it was using 5005. I will test it with higher number not in this range. But we know it may fail as any developer may have process running on this port.

2020-05-04 17:38 UTC, amamounelsayed commented on src/test/java/com/microsoft/azure/functions/worker/test/utilities/FunctionsTestHost.java
> +    public int getPort() { return 55005; }
I believe we should use between 49152-65535
https://www.sciencedirect.com/topics/computer-science/registered-port
Dynamic ports—Ports in the range 49152 to 65535 are not assigned, controlled, or registered. They are used for temporary or private ports. They are also known as private or non-reserved ports. Clients should choose ephemeral port numbers from this range, but many systems do not.

2020-05-04 17:39 UTC, amamounelsayed commented on src/test/java/com/microsoft/azure/functions/worker/test/utilities/FunctionsTestHost.java
> +    public int getPort() { return 55005; }
What do you think?

2020-05-05 03:38 UTC, TsuyoshiUshio reviewed
Leave one comment. Port test works perfectly in my enviornment.

2020-05-05 03:38 UTC, TsuyoshiUshio commented on src/test/java/com/microsoft/azure/functions/worker/test/utilities/FunctionsTestHost.java
> +        return (int) list.get(rand.nextInt(list.size()));
It could choose the same Port number, after exception happens. 
For example, we could have a port number list as a instance variable of this class with current position. 
current position is 0 at first, once exception happens, it will be incremented. However, I don't care which logic is it. :)

2020-05-05 20:21 UTC, amamounelsayed commented
Closing this PR for sake of https://github.com/TsuyoshiUshio/azure-functions-java-worker/pull/2

2020-05-05 20:21 UTC, closed without merging